# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  # Every Vagrant virtual environment requires a box to build off of.
  #

  config.vm.box = "storax/ubuntu-14.04.2-server-amd64"
  config.vm.provider "vmware_fusion" do |v, override|
      override.vm.box_url = "https://oss-binaries.phusionpassenger.com/vagrant/boxes/latest/ubuntu-14.04-amd64-vmwarefusion.box"
  end

  # Support for vagrant-libvirt provider (kvm)
  config.vm.provider :libvirt do |v, override|
      override.vm.box = "pcp/basebox-ubuntu-trusty"
  end

  # single node Contrail with openstack Node
  #
  config.vm.define "contrail1", primary: true do |contrail|
    contrail.vm.network "private_network", ip: "192.168.10.100"
    contrail.vm.provider "virtualbox" do |v|
      v.memory = 8096
      v.cpus = 4
    end

    contrail.vm.provider "vmware_fusion" do |vf|
        vf.vmx["numvcpus"] = "4"
        vf.vmx["memsize"] = "8096"
        vf.vmx["vhv.enable"] = "TRUE"
    end
  end

#  config.vm.define "contrail2", primary: true do |contrail|
#
#    contrail.vm.provider "virtualbox" do |v|
#      v.memory = 8096
#      v.cpus = 2
#    end
#
#    contrail.vm.provider "vmware_fusion" do |vf|
#        vf.vmx["numvcpus"] = "4"
#        vf.vmx["memsize"] = "8096"
#        vf.vmx["vhv.enable"] = "TRUE"
#    end
#    contrail.vm.network "private_network", ip: "192.168.100.12"
#
#  end

end
